# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u -t github.com/golang/protobuf
      - run: go get -u -t google.golang.org/grpc
      - run: go install github.com/golang/protobuf/protoc-gen-go/
      - run: sudo apt-get update
      - run: sudo apt-get install -y protobuf-compiler
      - run: make
      - run: make test
      - run: ./ci/bootstrap.sh docs/hegeIV/map-calaquyr.json docs/hegeIV/definitions/ /tmp/
