# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: |
          go get -v -t -d ./...
          go get -u -t github.com/golang/protobuf
          go get -u -t google.golang.org/grpc
          go install github.com/golang/protobuf/protoc-gen-go/
      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            protobuf-compiler \
            librocksdb5.17 \
            librocksdb-dev
      - run: make
      - run: make test
      - run: make benchmark
      - run: |
          DST=$(mktemp -d)
          ./ci/bootstrap.sh \
            docs/hegeIV/map-calaquyr.json \
            docs/hegeIV/definitions \
            docs/hegeIV/lang \
            "${DST}"
      - run:
          name: Code Coverage
          command: |
            rm profile.out
            bash <(curl -s https://codecov.io/bash)
          when: on_success
